### ISSUE TITLE
[BUG] [Control panel] - The buttons with confirmations no longer work in modern browsers

### ISSUE THREAD

**Issue by Alexander90281** [AgustinSRG/Showdown-ChatBot#10]
Buenos días, disculpa la molestia, teníamos configurado un bot para la sala de hispano, en Pokémon showdown, ahora que quisimos activarlo ya no conecta con el server, parece que es un problema con el protocolo Ws y WSS crees que podrías ayudarme?

**Comment by AgustinSRG** [comment]
Buenas @Alexander90281. Lo más probable es que no hayas especificado correctamente los detalles de conexión al servidor de Pokemon Showdown al que quieres que el bot se conecte.

Para cambiar estos detalles de conexión debes ir al panel de control del bot en la opción `Bot Configuration`.

Si se trata del servidor principal de Pokemon Showdown, estos serían los detalles de conexión que necesitas:

 - Server: `sim3.psim.us`
 - Port: `443`
 - Server-ID: `showdown`
 - Conexión segura mediante TLS

![image](https://github.com/user-attachments/assets/4ec24a0f-85b3-4d0c-8790-a25f2203c090)

**Comment by Alexander90281** [comment]
Hola, primero, agradecer tu valioso tiempo.
Te comento que ya puse esa configuración y sigue sin conectar, si gusta te doy acceso para que le eches una revisión si es posible.
![image](https://github.com/user-attachments/assets/03ddf519-d3b7-4949-8d7f-899eea867317)
![image](https://github.com/user-attachments/assets/449459e0-3d36-4946-bfd5-9e6f5d82eb65)

**Comment by Alexander90281** [comment]
![image](https://github.com/user-attachments/assets/2e6ba09e-fb5a-406c-8b41-dde91c9b8499)

**Comment by AgustinSRG** [comment]
He visto que hay un bug en el botón "Restart Bot" como consecuencia de la eliminación del evento `DOMNodeInserted` en los navegadores web. Seguramente por ello los cambios no se aplican. Solucionaré el bug lo antes posible y estará arreglado en la siguiente versión.

De momento, reinicia el proceso del bot manualmente o mediante la opción `Exit Process` dentro de la opción `Admin` del panel de control.

**Comment by AgustinSRG** [comment]
El commit [3d8e975](https://github.com/AgustinSRG/Showdown-ChatBot/commit/3d8e975bf753244f89ef22041b96ee4eb89949bb) debería haberlo arreglado.

Si tras actualizar sigue sin conectar, podría tratarse de un error de DNS o una firewall bloqueando la conexión. En ese caso recomiendo revisar los logs de seguridad (`Security Log`) para comprobar la causa del error.

**Comment by Alexander90281** [comment]
![image](https://github.com/user-attachments/assets/a51f9bc1-96d7-4c48-bdf6-df23b86a1b50)
Sigue sin conectar, crees que sea algo del codigo de github que deba actualizar?

**Comment by AgustinSRG** [comment]
Dale a `View Log` en el log de hoy (August 02, 2024). Ahí debería estar el log con la información del error.

El error que he solucionado antes provoca que al darle a "Restart Bot" te diga que no tienes acceso. Deberías actualizar el bot a la última versión. Si has clonado el repositorio de GitHub, valdría con hacer un pull a este repositorio:

```sh
git pull https://github.com/AgustinSRG/Showdown-ChatBot.git
```

Si estás usando la imagen de Docker, sería necesario hacer un `docker pull` a la imagen, y reiniciar el contenedor.

Si descargaste el repositorio como ZIP, es necesario volver a descargarlo y sobre-escribir los ficheros.

**Comment by Alexander90281** [comment]
![image](https://github.com/user-attachments/assets/f4859d1e-8eb8-4876-97f0-3c5a759f486e)
Yo hice el clone de este repositorio del bot de nosotros en Hispano, entonces no se si toca editar el codigo desde github o se puede sobreescribir

**Comment by AgustinSRG** [comment]
Si se trata de un Fork de este repositorio, puedes sincronizarlo con las herramientas que ofrece git (`git merge`) o desde la web usando la interfaz que ofrece GitHub. Te dejo una guía que ofrece GitHub: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Si es un proyecto a parte basado en este repositorio, cualquier error debe ser reportado al repositorio del proyecto que estés usando, no al que está basado, ya que perfectamente pueden haber reescrito gran parte del código, y por tanto, no tener nada que ver ya con el proyecto original.

**Comment by AgustinSRG** [comment]
Cierro esto, ya que el error ha sido corregido.

Si encuentras algún otro error en el proyecto, siéntete libre de abrir otro [Issue](https://github.com/AgustinSRG/Showdown-ChatBot/issues). Si tienes alguna duda o pregunta, puedes crear una [Discusión](https://github.com/AgustinSRG/Showdown-ChatBot/discussions).
