### ISSUE TITLE
disable from bot starting the timer in battle

### ISSUE THREAD

**Issue by LagendaBergerak** [AgustinSRG/Showdown-ChatBot#11]
Hi,

love the bot, working great, just want to know if there's a way to disable the bot from starting the timer in battle

![image](https://github.com/user-attachments/assets/0088d5ac-6417-4b7b-9032-394980f5a508)

i want to vs the bot without timer

thank you

**Comment by AgustinSRG** [comment]
Hi. Currently the bot uses the timer messages to know when to make decisions in battle.

If you are the bot owner and you have set your username as an excepted user in the Control panel of your bot (`Command Parser -> Permissions`) you can set the timer off with the command `.custom /timer off`, forcing the bot to send the command to disable the timer. But this may case the bot to get stuck waiting, so you may want to turn the timer on in that case with `.custom /timer on`.

I'll explore the option to use alternative ways for timing the battle decisions in order for the bot to not get stuck when the timer if off. I'll let you know in this issue when this feature is added.

**Comment by LagendaBergerak** [comment]
Hi thank you for responding, is this correct? because i'm unable to save the command,

![image](https://github.com/user-attachments/assets/c956da54-d70f-4a98-8d33-9b262f1cedfa)

the reason i want to play without a timer is to take my own time, and sometimes i get distracted or busy with other things, and would love to be able to pick up the game right from where it left off

thank you

**Comment by AgustinSRG** [comment]
> Hi thank you for responding, is this correct? because i'm unable to save the command,
> 
> ![image](https://private-user-images.githubusercontent.com/97179042/398436471-c956da54-d70f-4a98-8d33-9b262f1cedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQwNjgsIm5iZiI6MTczNTA1Mzc2OCwicGF0aCI6Ii85NzE3OTA0Mi8zOTg0MzY0NzEtYzk1NmRhNTQtZDcwZi00YTk4LThkMzMtOWIyNjJmMWNlZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDE1MjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmY2EzZTZlNjViZGZiZTNmNjExNzhlYmJiN2RmMTI0ZjBmMGQ0MjBlMGJjYzMxMDVmMDdiZmZmNmY0MmJiODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2VSzPGoaVO1SqRSvmR3ZwFLs6ppVMbDKESpK3qtiPVw)
> 
> the reason i want to play without a timer is to take my own time, and sometimes i get distracted or busy with other things, and would love to be able to pick up the game right from where it left off
> 
> thank you

You only need to put your username in the `Excepted Users` field. Then click `Save changes`. That will grant you permission to use any command of the bot. Then you can use `.custom /timer off` to turn off timer, and `.custom /timer on` to turn it back on, in case the bot gets stuck.

I'll let you know when I make the changes in order for the bot not to get stuck when timer is off.

**Comment by AgustinSRG** [comment]
I released a new version with this new feature: https://github.com/AgustinSRG/Showdown-ChatBot/releases/tag/v2.13.0

If you want to update the bot and do not know how, check the [FAQ](https://github.com/AgustinSRG/Showdown-ChatBot/wiki/Frequently-Asked-Questions#how-i-can-update-my-bot-if-i-have-an-old-version-but-i-do-not-want-to-lose-the-configuration).

You can turn the option off from the control panel, in the `Battle Bot` section. There should be a checkbox fot it. Uncheck it and click `Save Changes`.

![Screenshot](https://github.com/user-attachments/assets/9015b734-f7b4-44aa-b9e3-7853ac412418)

I'll leave this issue open for some days. If you find issues where the bot gets stuck in the new update, let me know by commenting in this issue.

**Comment by LagendaBergerak** [comment]
So Fast even it's the holidays

it works, will test it

![image](https://github.com/user-attachments/assets/7a70752b-57bf-4913-9f7b-fdb5ba8fb14b)


Thank you very much
