### ISSUE TITLE
Suggestions to improve timers command

### ISSUE THREAD

**Issue by 4N5H64M3R** [AgustinSRG/Showdown-ChatBot#7]
Hi! I have a few suggestions to improve the timer command.

**Suggestion:** A timer note feature like `.timer <time>, <note>` e.g. `.timer 1h, Start an event` and make it possible to add multiple timers in a room and find which user added which timer with timer IDs and the timer list can be displayed like this:
`User5: .timers
|HTMLBox Table from Bot|
Time | User | Note | ID
30m 7s | User3 | Timer for my event | 0098
4h 9m 1s | User6 | (empty due to no note) | 0099`
and the users can also display timers by IDs e.g. `.displaytimer (timer id)`

Please add these if it's possible, it will help a lot. Thank you!

**Comment by AgustinSRG** [comment]
Hi. Thanks for the suggestion. I think this is a positive change to the timer command so I'm implementing it.

**Comment by AgustinSRG** [comment]
Support for multiple timers in a single room has been added to the bot.

The updated commands: https://github.com/AgustinSRG/Showdown-ChatBot/wiki/Commands-List#timers-module

The new command syntax has been made compatible with the older version, to prevent any disruption.

The user who started the timer is not a relevant value to store or show, considering you can check who set the timer by using the chat logs feature (either the built-in one in Pokemon Showdown ot the one available in the bot control panel), so I'm not adding that.

With that ready, I'm closing this issue. If you have any other suggestions feel free to share them via [issues](https://github.com/AgustinSRG/Showdown-ChatBot/issues) or [discussions](https://github.com/AgustinSRG/Showdown-ChatBot/discussions). Also, if you find any issue with the new changes, please open a new [issue](https://github.com/AgustinSRG/Showdown-ChatBot/issues) explaining the problem.
