### ISSUE TITLE
Add and remove points feature for tour leaderboard

### ISSUE THREAD

**Issue by 4N5H64M3R** [AgustinSRG/Showdown-ChatBot#8]
It would be cool if leaderboards had add points and remove points feature please try to add them. Thank you.

**Comment by AgustinSRG** [comment]
Hi. This is a feature that is already in the bot as part of the custom leaderboards module.

The tournament leaderboards module was made just for tournaments, and points are just computed from the tournaments stats, thats why you cannot add or remove them without breaking the tournaments stats.

That is why I added a separate module some months ago, but I forgot to update the commands list in the wiki, so I just updated it:

 - https://github.com/AgustinSRG/Showdown-ChatBot/wiki/Commands-List#custom-leaderboards-module

Let's say you have a room called `Tournaments`, in that case, run the following commands to enable a custom leaderboards table for that room (changing the parameter to the ones you want):

```
.tourldbcustom create, Tournaments, Tournaments
.tourldbcustom config, Tournaments, win: 5, final: 3, semi_final: 1
.tourldbcustom auto, Tournaments, on
```

You can also configure it via the control panel, in the `Tour Leaderboards (Custom)` tab.

Once you have it configured, you can use the `extrapoints` command to add / remove points manually. Examples:

```
.extrapoints Tournaments, Example User:5, Other User: 3
.extrapoints Tournaments, Example User:-2
```

Not sure if this is what you're looking for. If you have any questions or concerns feel free to comment below.

**Comment by 4N5H64M3R** [comment]
Thanks a lot, this is exactly what I was asking for.
